fix: `<AppForm form>` prop binding
Ignore tanstack form api related to arrays.
It solves this kind of error due to `z.array()` validators and tanstack form inference:

```
Error: src/component/modal/setting/tanstack_general_settings/general_settings.tsx(101,7): error TS2322: Type 'AppFieldExtendedReactFormApi<{ display: { general?: { experimentalFeatures?: { display: boolean; visible: boolean; open?: boolean | undefined; } | undefined; hidePanelsBar?: boolean | undefined; } | undefined; panels?: { ...; } | undefined; toolBarButtons?: { ...; } | undefined; }; ... 11 more ...; axis?: { ...; } |...' is not assignable to type 'AppFieldExtendedReactFormApi<any, any, any, FormAsyncValidateOrFn<any> | undefined, any, FormAsyncValidateOrFn<any> | undefined, any, FormAsyncValidateOrFn<any> | undefined, ... 5 more ..., { ...; }>'.
  Types of property 'pushFieldValue' are incompatible.
    Type '<TField extends "nuclei" | "externalAPIs" | "databases.data" | "infoBlock.fields" | "spectraColors.oneDimension" | "spectraColors.twoDimensions" | "spectraLabel.fields">(field: TField, value: (TField extends "display" | ... 223 more ... | `spectraLabel.fields[${number}].uuid` ? DeepRecord<...>[TField] : never) exten...' is not assignable to type '<TField extends never>(field: TField, value: any, options?: UpdateMetaOptions | undefined) => void'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'any' is not assignable to type 'never'.
```

Refs: https://github.com/cheminfo/nmrium/actions/runs/28363594700/job/84024046363?pr=4230